server:
  port: 9090

spring:
  application:
    name: demo-park-api

  web:
    locale-resolver: fixed
    locale: pt_BR

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?reWriteBatchedInserts=true
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:a}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update